### PR TITLE
Fix python 3 incompatibility

### PR DESCRIPTION
**Pull request by jseutter**
A quick fix to a python 3 import error

### CODE REVIEW

**Comment by pydanny** [comment]
Do tests pass?

**Comment by jseutter** [comment]
In short, I don't know.  I'm currently guessing at how to run the tests (the travis config looks out of date).  I tried 

python -m unittest test_django_mailgun.py

but now I'm getting an error about my django project not being set up.  Is test_django_mailgun.py the file that contains the tests?

**Comment by pydanny** [comment]
@jseutter can you contact me privately? Perhaps on email?

**Comment by jseutter** [comment]
Done :)..  check your email

**Pull request merged**
